package com.yc.shopping.dao;

import com.yc.shopping.bean.CommodityBasic;
import com.yc.shopping.bean.CommodityBasicExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CommodityBasicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_basic
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    long countByExample(CommodityBasicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_basic
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    int deleteByExample(CommodityBasicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_basic
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_basic
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    int insert(CommodityBasic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_basic
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    int insertSelective(CommodityBasic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_basic
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    List<CommodityBasic> selectByExample(CommodityBasicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_basic
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    CommodityBasic selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_basic
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    int updateByExampleSelective(@Param("record") CommodityBasic record, @Param("example") CommodityBasicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_basic
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    int updateByExample(@Param("record") CommodityBasic record, @Param("example") CommodityBasicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_basic
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    int updateByPrimaryKeySelective(CommodityBasic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_basic
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    int updateByPrimaryKey(CommodityBasic record);
}