package com.yc.shopping.dao;

import com.yc.shopping.bean.CommodityRecord;
import com.yc.shopping.bean.CommodityRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CommodityRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_record
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    long countByExample(CommodityRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_record
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    int deleteByExample(CommodityRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_record
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_record
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    int insert(CommodityRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_record
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    int insertSelective(CommodityRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_record
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    List<CommodityRecord> selectByExample(CommodityRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_record
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    CommodityRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_record
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    int updateByExampleSelective(@Param("record") CommodityRecord record, @Param("example") CommodityRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_record
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    int updateByExample(@Param("record") CommodityRecord record, @Param("example") CommodityRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_record
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    int updateByPrimaryKeySelective(CommodityRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_record
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    int updateByPrimaryKey(CommodityRecord record);
}