package com.yc.shopping.dao;

import com.yc.shopping.bean.CommodityDetail;
import com.yc.shopping.bean.CommodityDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CommodityDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_detail
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    long countByExample(CommodityDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_detail
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    int deleteByExample(CommodityDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_detail
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_detail
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    int insert(CommodityDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_detail
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    int insertSelective(CommodityDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_detail
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    List<CommodityDetail> selectByExample(CommodityDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_detail
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    CommodityDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_detail
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    int updateByExampleSelective(@Param("record") CommodityDetail record, @Param("example") CommodityDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_detail
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    int updateByExample(@Param("record") CommodityDetail record, @Param("example") CommodityDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_detail
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    int updateByPrimaryKeySelective(CommodityDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_detail
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    int updateByPrimaryKey(CommodityDetail record);
}