package com.yc.shopping.bean;

public class Cart {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.id
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.commodity_name
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    private String commodityName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.commodity_img
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    private String commodityImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.commodity_color
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    private String commodityColor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.commodity_size
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    private String commoditySize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.commodity_price
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    private Double commodityPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.commodity_num
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    private Integer commodityNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.commodity_total_prices
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    private Double commodityTotalPrices;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.user_id
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.keeperid
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    private Integer keeperid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.id
     *
     * @return the value of cart.id
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.id
     *
     * @param id the value for cart.id
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.commodity_name
     *
     * @return the value of cart.commodity_name
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public String getCommodityName() {
        return commodityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.commodity_name
     *
     * @param commodityName the value for cart.commodity_name
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public void setCommodityName(String commodityName) {
        this.commodityName = commodityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.commodity_img
     *
     * @return the value of cart.commodity_img
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public String getCommodityImg() {
        return commodityImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.commodity_img
     *
     * @param commodityImg the value for cart.commodity_img
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public void setCommodityImg(String commodityImg) {
        this.commodityImg = commodityImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.commodity_color
     *
     * @return the value of cart.commodity_color
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public String getCommodityColor() {
        return commodityColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.commodity_color
     *
     * @param commodityColor the value for cart.commodity_color
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public void setCommodityColor(String commodityColor) {
        this.commodityColor = commodityColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.commodity_size
     *
     * @return the value of cart.commodity_size
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public String getCommoditySize() {
        return commoditySize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.commodity_size
     *
     * @param commoditySize the value for cart.commodity_size
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public void setCommoditySize(String commoditySize) {
        this.commoditySize = commoditySize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.commodity_price
     *
     * @return the value of cart.commodity_price
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public Double getCommodityPrice() {
        return commodityPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.commodity_price
     *
     * @param commodityPrice the value for cart.commodity_price
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public void setCommodityPrice(Double commodityPrice) {
        this.commodityPrice = commodityPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.commodity_num
     *
     * @return the value of cart.commodity_num
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public Integer getCommodityNum() {
        return commodityNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.commodity_num
     *
     * @param commodityNum the value for cart.commodity_num
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public void setCommodityNum(Integer commodityNum) {
        this.commodityNum = commodityNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.commodity_total_prices
     *
     * @return the value of cart.commodity_total_prices
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public Double getCommodityTotalPrices() {
        return commodityTotalPrices;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.commodity_total_prices
     *
     * @param commodityTotalPrices the value for cart.commodity_total_prices
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public void setCommodityTotalPrices(Double commodityTotalPrices) {
        this.commodityTotalPrices = commodityTotalPrices;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.user_id
     *
     * @return the value of cart.user_id
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.user_id
     *
     * @param userId the value for cart.user_id
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.keeperid
     *
     * @return the value of cart.keeperid
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public Integer getKeeperid() {
        return keeperid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.keeperid
     *
     * @param keeperid the value for cart.keeperid
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public void setKeeperid(Integer keeperid) {
        this.keeperid = keeperid;
    }
}