package com.yc.shopping.bean;

import java.util.ArrayList;
import java.util.List;

public class CartExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cart
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cart
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cart
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public CartExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cart
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCommodityNameIsNull() {
            addCriterion("commodity_name is null");
            return (Criteria) this;
        }

        public Criteria andCommodityNameIsNotNull() {
            addCriterion("commodity_name is not null");
            return (Criteria) this;
        }

        public Criteria andCommodityNameEqualTo(String value) {
            addCriterion("commodity_name =", value, "commodityName");
            return (Criteria) this;
        }

        public Criteria andCommodityNameNotEqualTo(String value) {
            addCriterion("commodity_name <>", value, "commodityName");
            return (Criteria) this;
        }

        public Criteria andCommodityNameGreaterThan(String value) {
            addCriterion("commodity_name >", value, "commodityName");
            return (Criteria) this;
        }

        public Criteria andCommodityNameGreaterThanOrEqualTo(String value) {
            addCriterion("commodity_name >=", value, "commodityName");
            return (Criteria) this;
        }

        public Criteria andCommodityNameLessThan(String value) {
            addCriterion("commodity_name <", value, "commodityName");
            return (Criteria) this;
        }

        public Criteria andCommodityNameLessThanOrEqualTo(String value) {
            addCriterion("commodity_name <=", value, "commodityName");
            return (Criteria) this;
        }

        public Criteria andCommodityNameLike(String value) {
            addCriterion("commodity_name like", value, "commodityName");
            return (Criteria) this;
        }

        public Criteria andCommodityNameNotLike(String value) {
            addCriterion("commodity_name not like", value, "commodityName");
            return (Criteria) this;
        }

        public Criteria andCommodityNameIn(List<String> values) {
            addCriterion("commodity_name in", values, "commodityName");
            return (Criteria) this;
        }

        public Criteria andCommodityNameNotIn(List<String> values) {
            addCriterion("commodity_name not in", values, "commodityName");
            return (Criteria) this;
        }

        public Criteria andCommodityNameBetween(String value1, String value2) {
            addCriterion("commodity_name between", value1, value2, "commodityName");
            return (Criteria) this;
        }

        public Criteria andCommodityNameNotBetween(String value1, String value2) {
            addCriterion("commodity_name not between", value1, value2, "commodityName");
            return (Criteria) this;
        }

        public Criteria andCommodityImgIsNull() {
            addCriterion("commodity_img is null");
            return (Criteria) this;
        }

        public Criteria andCommodityImgIsNotNull() {
            addCriterion("commodity_img is not null");
            return (Criteria) this;
        }

        public Criteria andCommodityImgEqualTo(String value) {
            addCriterion("commodity_img =", value, "commodityImg");
            return (Criteria) this;
        }

        public Criteria andCommodityImgNotEqualTo(String value) {
            addCriterion("commodity_img <>", value, "commodityImg");
            return (Criteria) this;
        }

        public Criteria andCommodityImgGreaterThan(String value) {
            addCriterion("commodity_img >", value, "commodityImg");
            return (Criteria) this;
        }

        public Criteria andCommodityImgGreaterThanOrEqualTo(String value) {
            addCriterion("commodity_img >=", value, "commodityImg");
            return (Criteria) this;
        }

        public Criteria andCommodityImgLessThan(String value) {
            addCriterion("commodity_img <", value, "commodityImg");
            return (Criteria) this;
        }

        public Criteria andCommodityImgLessThanOrEqualTo(String value) {
            addCriterion("commodity_img <=", value, "commodityImg");
            return (Criteria) this;
        }

        public Criteria andCommodityImgLike(String value) {
            addCriterion("commodity_img like", value, "commodityImg");
            return (Criteria) this;
        }

        public Criteria andCommodityImgNotLike(String value) {
            addCriterion("commodity_img not like", value, "commodityImg");
            return (Criteria) this;
        }

        public Criteria andCommodityImgIn(List<String> values) {
            addCriterion("commodity_img in", values, "commodityImg");
            return (Criteria) this;
        }

        public Criteria andCommodityImgNotIn(List<String> values) {
            addCriterion("commodity_img not in", values, "commodityImg");
            return (Criteria) this;
        }

        public Criteria andCommodityImgBetween(String value1, String value2) {
            addCriterion("commodity_img between", value1, value2, "commodityImg");
            return (Criteria) this;
        }

        public Criteria andCommodityImgNotBetween(String value1, String value2) {
            addCriterion("commodity_img not between", value1, value2, "commodityImg");
            return (Criteria) this;
        }

        public Criteria andCommodityColorIsNull() {
            addCriterion("commodity_color is null");
            return (Criteria) this;
        }

        public Criteria andCommodityColorIsNotNull() {
            addCriterion("commodity_color is not null");
            return (Criteria) this;
        }

        public Criteria andCommodityColorEqualTo(String value) {
            addCriterion("commodity_color =", value, "commodityColor");
            return (Criteria) this;
        }

        public Criteria andCommodityColorNotEqualTo(String value) {
            addCriterion("commodity_color <>", value, "commodityColor");
            return (Criteria) this;
        }

        public Criteria andCommodityColorGreaterThan(String value) {
            addCriterion("commodity_color >", value, "commodityColor");
            return (Criteria) this;
        }

        public Criteria andCommodityColorGreaterThanOrEqualTo(String value) {
            addCriterion("commodity_color >=", value, "commodityColor");
            return (Criteria) this;
        }

        public Criteria andCommodityColorLessThan(String value) {
            addCriterion("commodity_color <", value, "commodityColor");
            return (Criteria) this;
        }

        public Criteria andCommodityColorLessThanOrEqualTo(String value) {
            addCriterion("commodity_color <=", value, "commodityColor");
            return (Criteria) this;
        }

        public Criteria andCommodityColorLike(String value) {
            addCriterion("commodity_color like", value, "commodityColor");
            return (Criteria) this;
        }

        public Criteria andCommodityColorNotLike(String value) {
            addCriterion("commodity_color not like", value, "commodityColor");
            return (Criteria) this;
        }

        public Criteria andCommodityColorIn(List<String> values) {
            addCriterion("commodity_color in", values, "commodityColor");
            return (Criteria) this;
        }

        public Criteria andCommodityColorNotIn(List<String> values) {
            addCriterion("commodity_color not in", values, "commodityColor");
            return (Criteria) this;
        }

        public Criteria andCommodityColorBetween(String value1, String value2) {
            addCriterion("commodity_color between", value1, value2, "commodityColor");
            return (Criteria) this;
        }

        public Criteria andCommodityColorNotBetween(String value1, String value2) {
            addCriterion("commodity_color not between", value1, value2, "commodityColor");
            return (Criteria) this;
        }

        public Criteria andCommoditySizeIsNull() {
            addCriterion("commodity_size is null");
            return (Criteria) this;
        }

        public Criteria andCommoditySizeIsNotNull() {
            addCriterion("commodity_size is not null");
            return (Criteria) this;
        }

        public Criteria andCommoditySizeEqualTo(String value) {
            addCriterion("commodity_size =", value, "commoditySize");
            return (Criteria) this;
        }

        public Criteria andCommoditySizeNotEqualTo(String value) {
            addCriterion("commodity_size <>", value, "commoditySize");
            return (Criteria) this;
        }

        public Criteria andCommoditySizeGreaterThan(String value) {
            addCriterion("commodity_size >", value, "commoditySize");
            return (Criteria) this;
        }

        public Criteria andCommoditySizeGreaterThanOrEqualTo(String value) {
            addCriterion("commodity_size >=", value, "commoditySize");
            return (Criteria) this;
        }

        public Criteria andCommoditySizeLessThan(String value) {
            addCriterion("commodity_size <", value, "commoditySize");
            return (Criteria) this;
        }

        public Criteria andCommoditySizeLessThanOrEqualTo(String value) {
            addCriterion("commodity_size <=", value, "commoditySize");
            return (Criteria) this;
        }

        public Criteria andCommoditySizeLike(String value) {
            addCriterion("commodity_size like", value, "commoditySize");
            return (Criteria) this;
        }

        public Criteria andCommoditySizeNotLike(String value) {
            addCriterion("commodity_size not like", value, "commoditySize");
            return (Criteria) this;
        }

        public Criteria andCommoditySizeIn(List<String> values) {
            addCriterion("commodity_size in", values, "commoditySize");
            return (Criteria) this;
        }

        public Criteria andCommoditySizeNotIn(List<String> values) {
            addCriterion("commodity_size not in", values, "commoditySize");
            return (Criteria) this;
        }

        public Criteria andCommoditySizeBetween(String value1, String value2) {
            addCriterion("commodity_size between", value1, value2, "commoditySize");
            return (Criteria) this;
        }

        public Criteria andCommoditySizeNotBetween(String value1, String value2) {
            addCriterion("commodity_size not between", value1, value2, "commoditySize");
            return (Criteria) this;
        }

        public Criteria andCommodityPriceIsNull() {
            addCriterion("commodity_price is null");
            return (Criteria) this;
        }

        public Criteria andCommodityPriceIsNotNull() {
            addCriterion("commodity_price is not null");
            return (Criteria) this;
        }

        public Criteria andCommodityPriceEqualTo(Double value) {
            addCriterion("commodity_price =", value, "commodityPrice");
            return (Criteria) this;
        }

        public Criteria andCommodityPriceNotEqualTo(Double value) {
            addCriterion("commodity_price <>", value, "commodityPrice");
            return (Criteria) this;
        }

        public Criteria andCommodityPriceGreaterThan(Double value) {
            addCriterion("commodity_price >", value, "commodityPrice");
            return (Criteria) this;
        }

        public Criteria andCommodityPriceGreaterThanOrEqualTo(Double value) {
            addCriterion("commodity_price >=", value, "commodityPrice");
            return (Criteria) this;
        }

        public Criteria andCommodityPriceLessThan(Double value) {
            addCriterion("commodity_price <", value, "commodityPrice");
            return (Criteria) this;
        }

        public Criteria andCommodityPriceLessThanOrEqualTo(Double value) {
            addCriterion("commodity_price <=", value, "commodityPrice");
            return (Criteria) this;
        }

        public Criteria andCommodityPriceIn(List<Double> values) {
            addCriterion("commodity_price in", values, "commodityPrice");
            return (Criteria) this;
        }

        public Criteria andCommodityPriceNotIn(List<Double> values) {
            addCriterion("commodity_price not in", values, "commodityPrice");
            return (Criteria) this;
        }

        public Criteria andCommodityPriceBetween(Double value1, Double value2) {
            addCriterion("commodity_price between", value1, value2, "commodityPrice");
            return (Criteria) this;
        }

        public Criteria andCommodityPriceNotBetween(Double value1, Double value2) {
            addCriterion("commodity_price not between", value1, value2, "commodityPrice");
            return (Criteria) this;
        }

        public Criteria andCommodityNumIsNull() {
            addCriterion("commodity_num is null");
            return (Criteria) this;
        }

        public Criteria andCommodityNumIsNotNull() {
            addCriterion("commodity_num is not null");
            return (Criteria) this;
        }

        public Criteria andCommodityNumEqualTo(Integer value) {
            addCriterion("commodity_num =", value, "commodityNum");
            return (Criteria) this;
        }

        public Criteria andCommodityNumNotEqualTo(Integer value) {
            addCriterion("commodity_num <>", value, "commodityNum");
            return (Criteria) this;
        }

        public Criteria andCommodityNumGreaterThan(Integer value) {
            addCriterion("commodity_num >", value, "commodityNum");
            return (Criteria) this;
        }

        public Criteria andCommodityNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("commodity_num >=", value, "commodityNum");
            return (Criteria) this;
        }

        public Criteria andCommodityNumLessThan(Integer value) {
            addCriterion("commodity_num <", value, "commodityNum");
            return (Criteria) this;
        }

        public Criteria andCommodityNumLessThanOrEqualTo(Integer value) {
            addCriterion("commodity_num <=", value, "commodityNum");
            return (Criteria) this;
        }

        public Criteria andCommodityNumIn(List<Integer> values) {
            addCriterion("commodity_num in", values, "commodityNum");
            return (Criteria) this;
        }

        public Criteria andCommodityNumNotIn(List<Integer> values) {
            addCriterion("commodity_num not in", values, "commodityNum");
            return (Criteria) this;
        }

        public Criteria andCommodityNumBetween(Integer value1, Integer value2) {
            addCriterion("commodity_num between", value1, value2, "commodityNum");
            return (Criteria) this;
        }

        public Criteria andCommodityNumNotBetween(Integer value1, Integer value2) {
            addCriterion("commodity_num not between", value1, value2, "commodityNum");
            return (Criteria) this;
        }

        public Criteria andCommodityTotalPricesIsNull() {
            addCriterion("commodity_total_prices is null");
            return (Criteria) this;
        }

        public Criteria andCommodityTotalPricesIsNotNull() {
            addCriterion("commodity_total_prices is not null");
            return (Criteria) this;
        }

        public Criteria andCommodityTotalPricesEqualTo(Double value) {
            addCriterion("commodity_total_prices =", value, "commodityTotalPrices");
            return (Criteria) this;
        }

        public Criteria andCommodityTotalPricesNotEqualTo(Double value) {
            addCriterion("commodity_total_prices <>", value, "commodityTotalPrices");
            return (Criteria) this;
        }

        public Criteria andCommodityTotalPricesGreaterThan(Double value) {
            addCriterion("commodity_total_prices >", value, "commodityTotalPrices");
            return (Criteria) this;
        }

        public Criteria andCommodityTotalPricesGreaterThanOrEqualTo(Double value) {
            addCriterion("commodity_total_prices >=", value, "commodityTotalPrices");
            return (Criteria) this;
        }

        public Criteria andCommodityTotalPricesLessThan(Double value) {
            addCriterion("commodity_total_prices <", value, "commodityTotalPrices");
            return (Criteria) this;
        }

        public Criteria andCommodityTotalPricesLessThanOrEqualTo(Double value) {
            addCriterion("commodity_total_prices <=", value, "commodityTotalPrices");
            return (Criteria) this;
        }

        public Criteria andCommodityTotalPricesIn(List<Double> values) {
            addCriterion("commodity_total_prices in", values, "commodityTotalPrices");
            return (Criteria) this;
        }

        public Criteria andCommodityTotalPricesNotIn(List<Double> values) {
            addCriterion("commodity_total_prices not in", values, "commodityTotalPrices");
            return (Criteria) this;
        }

        public Criteria andCommodityTotalPricesBetween(Double value1, Double value2) {
            addCriterion("commodity_total_prices between", value1, value2, "commodityTotalPrices");
            return (Criteria) this;
        }

        public Criteria andCommodityTotalPricesNotBetween(Double value1, Double value2) {
            addCriterion("commodity_total_prices not between", value1, value2, "commodityTotalPrices");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andKeeperidIsNull() {
            addCriterion("keeperid is null");
            return (Criteria) this;
        }

        public Criteria andKeeperidIsNotNull() {
            addCriterion("keeperid is not null");
            return (Criteria) this;
        }

        public Criteria andKeeperidEqualTo(Integer value) {
            addCriterion("keeperid =", value, "keeperid");
            return (Criteria) this;
        }

        public Criteria andKeeperidNotEqualTo(Integer value) {
            addCriterion("keeperid <>", value, "keeperid");
            return (Criteria) this;
        }

        public Criteria andKeeperidGreaterThan(Integer value) {
            addCriterion("keeperid >", value, "keeperid");
            return (Criteria) this;
        }

        public Criteria andKeeperidGreaterThanOrEqualTo(Integer value) {
            addCriterion("keeperid >=", value, "keeperid");
            return (Criteria) this;
        }

        public Criteria andKeeperidLessThan(Integer value) {
            addCriterion("keeperid <", value, "keeperid");
            return (Criteria) this;
        }

        public Criteria andKeeperidLessThanOrEqualTo(Integer value) {
            addCriterion("keeperid <=", value, "keeperid");
            return (Criteria) this;
        }

        public Criteria andKeeperidIn(List<Integer> values) {
            addCriterion("keeperid in", values, "keeperid");
            return (Criteria) this;
        }

        public Criteria andKeeperidNotIn(List<Integer> values) {
            addCriterion("keeperid not in", values, "keeperid");
            return (Criteria) this;
        }

        public Criteria andKeeperidBetween(Integer value1, Integer value2) {
            addCriterion("keeperid between", value1, value2, "keeperid");
            return (Criteria) this;
        }

        public Criteria andKeeperidNotBetween(Integer value1, Integer value2) {
            addCriterion("keeperid not between", value1, value2, "keeperid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cart
     *
     * @mbg.generated do_not_delete_during_merge Sun Jun 23 21:58:52 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cart
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}