package com.yc.shopping.bean;

public class Collect {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect.id
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect.userid
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect.keeperid
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    private Integer keeperid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect.commodityBasicid
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    private Integer commoditybasicid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect.id
     *
     * @return the value of collect.id
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect.id
     *
     * @param id the value for collect.id
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect.userid
     *
     * @return the value of collect.userid
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect.userid
     *
     * @param userid the value for collect.userid
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect.keeperid
     *
     * @return the value of collect.keeperid
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public Integer getKeeperid() {
        return keeperid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect.keeperid
     *
     * @param keeperid the value for collect.keeperid
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public void setKeeperid(Integer keeperid) {
        this.keeperid = keeperid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect.commodityBasicid
     *
     * @return the value of collect.commodityBasicid
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public Integer getCommoditybasicid() {
        return commoditybasicid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect.commodityBasicid
     *
     * @param commoditybasicid the value for collect.commodityBasicid
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public void setCommoditybasicid(Integer commoditybasicid) {
        this.commoditybasicid = commoditybasicid;
    }
}