package com.yc.shopping.bean;

public class CommodityDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_detail.id
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_detail.basicid
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    private Integer basicid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_detail.status
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    private Boolean status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_detail.orderid
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    private Integer orderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_detail.commandid
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    private Integer commandid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_detail.collectedid
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    private Integer collectedid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_detail.keeperid
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    private Integer keeperid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_detail.id
     *
     * @return the value of commodity_detail.id
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_detail.id
     *
     * @param id the value for commodity_detail.id
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_detail.basicid
     *
     * @return the value of commodity_detail.basicid
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public Integer getBasicid() {
        return basicid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_detail.basicid
     *
     * @param basicid the value for commodity_detail.basicid
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public void setBasicid(Integer basicid) {
        this.basicid = basicid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_detail.status
     *
     * @return the value of commodity_detail.status
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_detail.status
     *
     * @param status the value for commodity_detail.status
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_detail.orderid
     *
     * @return the value of commodity_detail.orderid
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_detail.orderid
     *
     * @param orderid the value for commodity_detail.orderid
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_detail.commandid
     *
     * @return the value of commodity_detail.commandid
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public Integer getCommandid() {
        return commandid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_detail.commandid
     *
     * @param commandid the value for commodity_detail.commandid
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public void setCommandid(Integer commandid) {
        this.commandid = commandid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_detail.collectedid
     *
     * @return the value of commodity_detail.collectedid
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public Integer getCollectedid() {
        return collectedid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_detail.collectedid
     *
     * @param collectedid the value for commodity_detail.collectedid
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public void setCollectedid(Integer collectedid) {
        this.collectedid = collectedid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_detail.keeperid
     *
     * @return the value of commodity_detail.keeperid
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public Integer getKeeperid() {
        return keeperid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_detail.keeperid
     *
     * @param keeperid the value for commodity_detail.keeperid
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public void setKeeperid(Integer keeperid) {
        this.keeperid = keeperid;
    }
}