package com.yc.shopping.bean;

import java.util.Date;

public class CommodityCommand {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_command.id
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_command.userid
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_command.content
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_command.time
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_command.id
     *
     * @return the value of commodity_command.id
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_command.id
     *
     * @param id the value for commodity_command.id
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_command.userid
     *
     * @return the value of commodity_command.userid
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_command.userid
     *
     * @param userid the value for commodity_command.userid
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_command.content
     *
     * @return the value of commodity_command.content
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_command.content
     *
     * @param content the value for commodity_command.content
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_command.time
     *
     * @return the value of commodity_command.time
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_command.time
     *
     * @param time the value for commodity_command.time
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public void setTime(Date time) {
        this.time = time;
    }
}