package com.yc.shopping.bean;

public class CommodityBasic {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_basic.id
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_basic.keeper_id
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    private Integer keeperId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_basic.sort
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    private String sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_basic.brand
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    private String brand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_basic.size
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    private String size;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_basic.color
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    private String color;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_basic.number
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    private Integer number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_basic.price
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_basic.mainimg
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    private String mainimg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_basic.otherimgf
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    private String otherimgf;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_basic.otherimgs
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    private String otherimgs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_basic.otherimgt
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    private String otherimgt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_basic.otherimgfo
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    private String otherimgfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_basic.id
     *
     * @return the value of commodity_basic.id
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_basic.id
     *
     * @param id the value for commodity_basic.id
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_basic.keeper_id
     *
     * @return the value of commodity_basic.keeper_id
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public Integer getKeeperId() {
        return keeperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_basic.keeper_id
     *
     * @param keeperId the value for commodity_basic.keeper_id
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public void setKeeperId(Integer keeperId) {
        this.keeperId = keeperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_basic.sort
     *
     * @return the value of commodity_basic.sort
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public String getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_basic.sort
     *
     * @param sort the value for commodity_basic.sort
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public void setSort(String sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_basic.brand
     *
     * @return the value of commodity_basic.brand
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_basic.brand
     *
     * @param brand the value for commodity_basic.brand
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public void setBrand(String brand) {
        this.brand = brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_basic.size
     *
     * @return the value of commodity_basic.size
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public String getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_basic.size
     *
     * @param size the value for commodity_basic.size
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public void setSize(String size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_basic.color
     *
     * @return the value of commodity_basic.color
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_basic.color
     *
     * @param color the value for commodity_basic.color
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public void setColor(String color) {
        this.color = color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_basic.number
     *
     * @return the value of commodity_basic.number
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_basic.number
     *
     * @param number the value for commodity_basic.number
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_basic.price
     *
     * @return the value of commodity_basic.price
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_basic.price
     *
     * @param price the value for commodity_basic.price
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_basic.mainimg
     *
     * @return the value of commodity_basic.mainimg
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public String getMainimg() {
        return mainimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_basic.mainimg
     *
     * @param mainimg the value for commodity_basic.mainimg
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public void setMainimg(String mainimg) {
        this.mainimg = mainimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_basic.otherimgf
     *
     * @return the value of commodity_basic.otherimgf
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public String getOtherimgf() {
        return otherimgf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_basic.otherimgf
     *
     * @param otherimgf the value for commodity_basic.otherimgf
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public void setOtherimgf(String otherimgf) {
        this.otherimgf = otherimgf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_basic.otherimgs
     *
     * @return the value of commodity_basic.otherimgs
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public String getOtherimgs() {
        return otherimgs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_basic.otherimgs
     *
     * @param otherimgs the value for commodity_basic.otherimgs
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public void setOtherimgs(String otherimgs) {
        this.otherimgs = otherimgs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_basic.otherimgt
     *
     * @return the value of commodity_basic.otherimgt
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public String getOtherimgt() {
        return otherimgt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_basic.otherimgt
     *
     * @param otherimgt the value for commodity_basic.otherimgt
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public void setOtherimgt(String otherimgt) {
        this.otherimgt = otherimgt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_basic.otherimgfo
     *
     * @return the value of commodity_basic.otherimgfo
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public String getOtherimgfo() {
        return otherimgfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_basic.otherimgfo
     *
     * @param otherimgfo the value for commodity_basic.otherimgfo
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public void setOtherimgfo(String otherimgfo) {
        this.otherimgfo = otherimgfo;
    }
}