package com.yc.shopping.bean;

public class CommodityRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_record.id
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_record.userid
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_record.commodityid
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    private Integer commodityid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_record.orderid
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    private Integer orderid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_record.id
     *
     * @return the value of commodity_record.id
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_record.id
     *
     * @param id the value for commodity_record.id
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_record.userid
     *
     * @return the value of commodity_record.userid
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_record.userid
     *
     * @param userid the value for commodity_record.userid
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_record.commodityid
     *
     * @return the value of commodity_record.commodityid
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public Integer getCommodityid() {
        return commodityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_record.commodityid
     *
     * @param commodityid the value for commodity_record.commodityid
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public void setCommodityid(Integer commodityid) {
        this.commodityid = commodityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_record.orderid
     *
     * @return the value of commodity_record.orderid
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_record.orderid
     *
     * @param orderid the value for commodity_record.orderid
     *
     * @mbg.generated Sun Jun 23 21:58:52 CST 2019
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }
}